### ISSUE TITLE
[Tracking] Deprecation of this package

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJSerialization.jl#18]
Opening this issue to track roll-out of the new serialization API initiated by @olivierlabayle .

To do, in order:

- [x] Create PR's for the MLJ manual updates: https://github.com/alan-turing-institute/MLJ.jl/pull/922
- [x] MLJBase: Merge https://github.com/JuliaAI/MLJBase.jl/pull/751 and tag 0.20 release (breaking)
- [x] MLJXGBoostInterface: Merge https://github.com/JuliaAI/MLJXGBoostInterface.jl/pull/14 and tag a new release (breaking)
- [x] MLJTuning: Merge: https://github.com/JuliaAI/MLJTuning.jl/pull/165 and tag a new release (breaking)
- [x] MLJEnsembles: https://github.com/JuliaAI/MLJEnsembles.jl/pull/15 (breaking)
- [x] MLJIteration: https://github.com/JuliaAI/MLJIteration.jl/pull/47 (breaking)
- [x] MLJSerialialization: Close #15, #16
- [x] MLJSerialization: Close https://github.com/JuliaAI/MLJSerialization.jl/issues/15
- [x] Archive MLJSerialization.jl repo
